export const IMAGES = {
  REACT: require('./assets/reactjs.png'),
  FB: require('./assets/fb.png'),
  ARROW: require('./assets/arrow.png'),
  ARROW_RIGHT: require('./assets/arrow-right.png'),
  MAP_MARKER: require('./assets/map-marker.png'),
  CLOSE: require('./assets/close.png'),
  SPEAKER: require('./assets/voice.png'),
  SAVE: require('./assets/save.png'),
  SEARCH: require('./assets/search.png'),
  EDIT: require('./assets/editIcon.png'),
  IMAGE: require('./assets/image.png'),
  ADD: require('./assets/add.png'),
  MINUS: require('./assets/minus.png'),
};
